# Generated by Django 5.2.1 on 2025-06-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10, verbose_name='Status do Leilão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('leiloeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leiloes_criados', to='usuarios.leiloeiroprofile', verbose_name='Leiloeiro Responsável')),
                ('produtos', models.ManyToManyField(related_name='leiloes_associados', to='produto.produto', verbose_name='Produtos do Leilão')),
            ],
            options={
                'verbose_name': 'Leilão',
                'verbose_name_plural': 'Leilões',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
