# Generated by Django 5.2.1 on 2025-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leiloeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Leiloeiro')),
                ('cell', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do Leiloeiro')),
            ],
            options={
                'verbose_name': 'Leiloeiro',
                'verbose_name_plural': 'Leiloeiros',
                'ordering': ['name'],
            },
        ),
    ]
