# Generated by Django 5.2.1 on 2025-06-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('leilao', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_lances', to='cliente.cliente')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='leilao.leilao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances_produto', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
            },
        ),
    ]
