# Generated by Django 5.2.1 on 2025-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('cell', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name', 'second_name'],
            },
        ),
    ]
