# Generated by Django 5.2.1 on 2025-06-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('cell', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do Cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cliente_app_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfis de Clientes',
                'ordering': ['name', 'second_name'],
            },
        ),
        migrations.CreateModel(
            name='LeiloeiroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Leiloeiro')),
                ('cell', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do Leiloeiro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_leiloeiro_app_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Leiloeiro',
                'verbose_name_plural': 'Perfis de Leiloeiros',
                'ordering': ['name'],
            },
        ),
    ]
