# Generated by Django 5.2.1 on 2025-06-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidade', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Inicial')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_LEILAO', 'Em Leilão'), ('VENDIDO', 'Vendido')], default='DISPONIVEL', max_length=10, verbose_name='Status do Produto')),
                ('modalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modalidade.modalidade', verbose_name='Modalidade')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
